// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/avatar/Avatar.vue')['default']
    Button: typeof import('./src/components/button/Button.vue')['default']
    Card: typeof import('./src/components/card/Card.vue')['default']
    Collapse: typeof import('./src/components/collapse/Collapse.vue')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    FamilyRow: typeof import('./src/components/family/FamilyRow.vue')['default']
    IconBiSearch: typeof import('~icons/bi/search')['default']
    Logo: typeof import('./src/components/images/Logo.vue')['default']
    Sidebar: typeof import('./src/components/layouts/sidebar/Sidebar.vue')['default']
    SidebarCreate: typeof import('./src/components/layouts/sidebar/SidebarCreate.vue')['default']
    SidebarItem: typeof import('./src/components/layouts/sidebar/SidebarItem.vue')['default']
    XInput: typeof import('./src/components/forms/XInput.vue')['default']
  }
}

export { }
