// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '$toast': (props: ToastProps) => void
    Avatar: typeof import('./src/components/avatar/Avatar.vue')['default']
    BackgroundGrid: typeof import('./src/components/editor/BackgroundGrid.vue')['default']
    Button: typeof import('./src/components/button/XButton.vue')['default']
    Card: typeof import('./src/components/card/Card.vue')['default']
    Collapse: typeof import('./src/components/collapse/Collapse.vue')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    EditorTopbar: typeof import('./src/components/editor/EditorTopbar.vue')['default']
    FamilyRow: typeof import('./src/components/family/FamilyRow.vue')['default']
    IconBiSearch: typeof import('~icons/bi/search')['default']
    IconBiX: typeof import('~icons/bi/x')['default']
    IconBiXLg: typeof import('~icons/bi/x-lg')['default']
    IconCarbonAddAlt: typeof import('~icons/carbon/add-alt')['default']
    IconCarbonAppConnectivity: typeof import('~icons/carbon/app-connectivity')['default']
    IconCarbonPlus: typeof import('~icons/carbon/plus')['default']
    IconCarbonX: typeof import('~icons/carbon/x')['default']
    Instruction: typeof import('./src/components/Toast/Instruction.vue')['default']
    Logo: typeof import('./src/components/images/Logo.vue')['default']
    Modal: typeof import('./src/components/modal/Modal.vue')['default']
    Sidebar: typeof import('./src/components/layouts/sidebar/Sidebar.vue')['default']
    SidebarCreate: typeof import('./src/components/layouts/sidebar/SidebarCreate.vue')['default']
    SidebarItem: typeof import('./src/components/layouts/sidebar/SidebarItem.vue')['default']
    Toast: typeof import('./src/components/Toast/Toast.vue')['default']
    ToastGroup: typeof import('./src/components/Toast/ToastGroup.vue')['default']
    TopbarMenu: typeof import('./src/components/menu/TopbarMenu.vue')['default']
    XButton: typeof import('./src/components/button/XButton.vue')['default']
    XInput: typeof import('./src/components/forms/XInput.vue')['default']
    XModal: typeof import('./src/components/modal/XModal.vue')['default']
    XPerson: typeof import('./src/components/editor/svg/XPerson.vue')['default']
  }
}

export { }
